# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := test
ARDUINO_LIBS := AUnit
include /home/docker/Arduino/libraries/EpoxyDuino/EpoxyDuino.mk
