pool: MyLocalPool

container:
  image: myworkregistry007.azurecr.io/iot_repo:DigitalSigning532
  endpoint: myWorkRegistry007
  options: -v /dev:/dev


steps:
- script: ls -l /dev/ttyACM0
  displayName: "Running script"

