pool: MyLocalAgent

trigger:
- main

pr:
- main

steps:
- task: UsePythonVersion@0
  displayName: ‘Manage Python Version’
  inputs:
  versionSpec: 3.7
  architecture: ‘x64’
- task: PythonScript@0
  displayName: ‘Search Django Project’
  inputs:
  scriptSource: ‘inline’
  script: |
 “““Search all subdirectories for `manage.py`.”””
 from glob import iglob
 from os import path
 # Python >= 3.5
 manage_py = next(iglob(path.join(‘**’, ‘manage.py’), recursive=True), None)
 if not manage_py:
 raise SystemExit(‘Could not find a Django project’)
 project_location = path.dirname(path.abspath(manage_py))
 print(‘Found Django project in’, project_location)
 print(‘##vso[task.setvariable variable=projectRoot]{}’.format(project_location))
- script: |
   pip install -r requirements.txt
   pip install unittest-xml-reporting
   displayName: ‘Install Python Prerequisites’
- script: |
   pip install pytest pytest-azurepipelines pytest-cov
   pytest -v — junitxml=junit/test-results.xml — cov — cov-report=xml — cov-report=html
   displayName: “Pytest Unit Test with Coverage”
   continueOnError: False
- task: PublishCodeCoverageResults@1
  displayName: ‘Publish Cobertura Coverage Report’
  inputs:
   codeCoverageTool: Cobertura
   summaryFileLocation: ‘$(System.DefaultWorkingDirectory)/**/coverage.xml’
   reportDirectory: ‘$(System.DefaultWorkingDirectory)/**/htmlcov’
